### PR TITLE
Added Cocoapods support, updated README

### PR DESCRIPTION
**Pull request by itchingpixels**
We're using cocoapods with our RN project, to streamline dependency management.

As a consequence, we need all further dependencies to be integrated as a pod, which is relatively easy to create.

The post-install hook seems to be necessary because of ZendeskSDK's weird config. I couldn't manage to get the project to compile without it.

### CODE REVIEW

**Comment by RobertSheaO** [comment]
Awesome! This was on my list of things todo. I'll pull it down and test/merge

**Comment by RobertSheaO** [comment]
@itchingpixels, could you clarify the aim of this pull request. Is it to remove the local dependency on the ZenDesk SDK, or to allow react-native-zendesk-support to be added as a pod dependency?

**Comment by itchingpixels** [comment]
We're not removing the local dependency if you're using react-native link,
it's still there and will need to be there.

But unfortunately we can not use the local dependency with Cocoapods, so
that needs to be imported as a pod, and the local dependency is ignored.

This is the way we have handled, and I have seen people handling external
dependencies with react-native projects.

For reference:
https://github.com/geektimecoil/react-native-onesignal/blob/master/react-native-onesignal.podspec
https://github.com/corymsmith/react-native-fabric/blob/master/ReactNativeFabric.podspec

Thanks!

**Comment by itchingpixels** [comment]
Cocoapods and react-native link doesn't work well together at the moment, so if somebody is using Cocoapods, they're automatically discarding the automatic integration on the iOS side that react-native link produces.

**Comment by RobertSheaO** [comment]
I integrated your changes into the latest release, 1.0.0

**Pull request closed without merging**
